# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_details_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='details',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='details_text',
            new_name='detail_text',
        ),
    ]
