# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20161114_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('C++', 'C++')], default='Python', max_length=64),
            preserve_default=False,
        ),
    ]
