# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='comic_alt',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
