# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_comic_comic_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_img', models.ImageField(upload_to='images/')),
                ('comic_alt', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='comic',
            name='comic_alt',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='comic_img',
        ),
        migrations.AddField(
            model_name='content',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.Comic'),
        ),
    ]
